title: "桑丹道人"
description: "桑丹道人之《桑丹笔记》系列"
remote_theme: just-the-docs/just-the-docs

# GitHub Pages 通常需要显式启用 remote_theme 插件
plugins:
  - jekyll-remote-theme

# 站点行为
markdown: kramdown

# Just the Docs：搜索
search_enabled: true


# hide collections
collections:
  posts:
    nav_exclude: true

# hide ebook posts
defaults:
  - scope:
      path: "ebook"
    values:
      nav_exclude: true

